server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: vod # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 10.134.151.254:8848 # nacos服务地址
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M

aliyun:
  vod:
    keyid: LTAI5tQdYwW8vuZuzGFXFBnc
    keysecret: wElL2XsCGdgad16AgP79BsEQxpPuqJ
    templateGroupId: c26de26c4bd5a926cd299342a4642c25 #转码模板组id
    workflowId: e5f9524e9a728c92fd4a3b7ee9451e59 #工作流id