server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: oss # 服务名
#spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.134.151.254:8848 # nacos服务地址

aliyun:
  oss:
    url: http://qqinstitute.oss-cn-beijing.aliyuncs.com/
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAI5tGGbifpikph8Nz1fqmE
    keysecret: wPOgoTdPML2MGxi3stbj3wnXVlEwk9
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: qqinstitute